Feature: 액티비티 카드 구현
Gila-part4/Gila-veta pull request #30
Opened 2024-07-12 14:47 UTC by sj0724

searchParam에 있는 값을 받아서 api 쿼리값으로 전달하고 있습니다.
<img width="1552" alt="스크린샷 2024-07-12 오후 11 45 39" src="https://github.com/user-attachments/assets/8b10daa6-5c2e-4526-b483-010918b2fd6c">
우선 이런 식으로 카드 스타일 적용시켜놨고 스켈레톤도 제작은 해놨는데 사용하는 방법은 논의가 필요할것 같습니다.

2024-07-13 06:27 UTC, kuum97 requested changes
👍

2024-07-13 06:27 UTC, kuum97 commented on app/(client)/(public)/(main)/_components/activity-container.tsx
import 절대 경로요! 뭔가 같은 폴더라서 이상하긴한데 혹시 그럴 일은 없겠지만 해당 컴포넌트가 다른 폴더로 갔을 때 영향이 없도록 수정하는게 좋을 것 같습니당

2024-07-14 02:03 UTC, sj0724 commented on app/(client)/(public)/(main)/_components/activity-container.tsx
말씀하신데로 경로 수정을 했는데 엄청 길어지긴 하네요,,,

2024-07-14 10:12 UTC, Batrnan approved these changes

2024-07-14 11:01 UTC, juan0444 approved these changes

2024-07-15 01:38 UTC, kuum97 approved these changes

2024-07-15 01:44 UTC, merged