Feat: review, reviewModal
Gila-part4/Gila-veta pull request #46
Opened 2024-07-16 03:04 UTC by sj0724

리뷰 4개만 먼저 서버렌더링하도록 설정했고 나머지 리뷰는 모달 통해서 클라이언트 리퀘스트 보내도록 설정했습니다.
페이지에서 넘겨주실 props는 activityId만 주시면 됩니다
아직 api에 리뷰 데이터를 안심어놔서 지금 mockdata로 해놨는데 이후에 데이터 생성하고 이 부분은 수정하겠습니다.

2024-07-16 10:57 UTC, sj0724 commented
추가적으로 공유 모달 구현했습니다. 카카오톡이랑 링크 복사만 추가했습니다!

2024-07-17 03:50 UTC, kuum97 reviewed
👍

2024-07-17 03:50 UTC, kuum97 commented on app/(client)/(public)/[activityId]/_components/review-container.tsx
목데이터를 제외하고 데이터를 주실 때 예를 들어 item의 경우 item이라는 변수명이 직접 사용되야 하거나 다른 변수와 구별이 필요한 상황이 아니라면 구조분해할당으로 주시는게 깔끔할 것 같습니다!

2024-07-17 03:50 UTC, kuum97 commented on app/layout.tsx
이 부분 오늘 미팅 때 설명해주시면 좋을것 같습니다!

2024-07-17 03:56 UTC, kuum97 requested changes

2024-07-17 03:56 UTC, kuum97 commented on app/(client)/(public)/[activityId]/_components/review-container.tsx
> +        {review.reviews.map((item) => (
여기서 목데이터지만 일단 리뷰배열을 바로 map으로 컴포넌트를 전해주시고 계신데 이러면 리뷰에 대한 map을 돌릴 때마다 컴포넌트 함수를 실행하여 비효율적인 것 같습니다. ReviewList라는 컴포넌트를 만드시고 내부에 
``` javascript
<ul>
   {reviews.map(({id, comment}) => <li key={id}>{comment}</li>) // 해당 <li>.. 부분을 ReviewItem 컴포넌트로 넣어주면 될거같습니다.
</ul>
```

2024-07-17 08:07 UTC, sj0724 commented on app/(client)/(public)/[activityId]/_components/review-container.tsx
> +        {review.reviews.map((item) => (
수정했습니다!

2024-07-18 03:56 UTC, juan0444 approved these changes

2024-07-27 05:43 UTC, closed without merging